spring:
  application:
    name: 'pagamento'
  datasource:
    url: jdbc:mysql://localhost:3306/alurafood-pagamento?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
